import Head from 'next/head'
import Image from 'next/image'
import Style from '../styles/Home.module.css'



// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div>
          <h2>This is good</h2>
          <p className={Style.header}>Hello</p>
          <Image src="/jigsmur1.jpg" width={196} height={100 }/>
          </div>
      
    </>
  )
}
